#!/bin/sh
#
# Vector Engine Driver
#
# Copyright (C) 2017-2018 NEC Corporation
# This file is part of VE Driver.
#
# VE Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# VE Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with the VE Driver; if not, see
# <http://www.gnu.org/licenses/>.
#

MODPROBE=/sbin/modprobe
MODNAME=ve_drv

cmd=$1
case "$cmd" in
start)
	echo "Loading ve_drv module"
	$MODPROBE $MODNAME
	;;
stop)
	echo "Unloading ve_drv module"
	$MODPROBE -r $MODNAME
	;;
*)
	echo "Usage $0 [start|stop]"
	exit 1
esac
